platform: linux

image_resource:
  type: mock
  source: { mirror_self: true }

params:
  ECHO_ME: "default text to echo from task config file"

run:
  path: sh
  args:
  - -cx
  - |
    echo "var: ${ECHO_ME}"
