---
resources:
  - name: larvel-websockets-git
    type: git
    icon: github
    source:
      uri: https://github.com/beyondcode/laravel-websockets.git

jobs:
  - name: test
    public: true
    plan:
      - get: larvel-websockets-git
        trigger: true
      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: php, tag: 7.2-cli }
          inputs:
            - name: larvel-websockets-git
          run:
            path: /bin/sh
            args:
              - -c
              - |
                apt-get update
                apt-get install -y git unzip

                EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)"
                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

                if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
                then
                    >&2 echo 'ERROR: Invalid installer checksum'
                    rm composer-setup.php
                    exit 1
                fi
                cd larvel-websockets-git

                composer install
                vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
